### ISSUE TITLE
branch unbiased-volume-opt does not exist

### ISSUE THREAD

**Issue by tli-loreal** [rgl-epfl/recursive_control_variates#1]
Hi,

I'm trying to install the repo, however the branch unbiased-volume-opt could not be found in mitsuba3, can you check it, please?

Bests,
Tao

**Comment by bathal1** [comment]
Sorry about that, it should be [there ](https://github.com/mitsuba-renderer/mitsuba3/tree/unbiased-volume-opt) now.

**Comment by tli-loreal** [comment]
Thanks a lot, I close the issue

**Comment by Yishun99** [comment]
Hi @bathal1 ,
I found this branch is hundreds commits behind master.
Are there any plans to merge the branch to mitsuba3 master? 
Thanks.

**Comment by bathal1** [comment]
Hi,
The plan is to eventually integrate this method in Mitsuba 3, but there is no timeline for this at the moment. Please feel free to open an issue on this repo if you run into problems due to the lag between this branch and `master`
